version: '3.9'

services:
  keycloak-api:
    build:
      context: ./keycloak-api
    ports:
      - "5000:5000"
    volumes:
      - ./keycloak-api:/app/api
    environment:      
      - FLASK_ENV=development
    command: sh -c "poetry install && poetry run python app.py"

  keycloak-web:
    build:
      context: ./keycloak-web
    ports:
      - "3000:3000"

  keycloak-auth:
    build:
      context: ./keycloak-auth
    environment:
      POSTGRES_DB: ${POSTGRESQL_DB}
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASS}
    volumes:
      - ./keycloak-auth/postgres_data:/var/lib/postgresql/data
    ports:
      - 8080:8080
    command:
      - start-dev

volumes:
  keycloak-auth_postgres_data:
