version: '3.9'

services:
  flask-api:
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - ./api:/app/api
    environment:      
      - FLASK_ENV=development
    command: sh -c "poetry install && poetry run python app.py"
